version: "1.0"
info:
  model: int-scaffold
packages:
- name: TestAutoCommitEnabled1809Project
  gitServerName: src_shared_GithubCtrl_Arti
  gitUrl: https://github.com/ArtiKhareNew
  gitUsername: ArtiKhareNew
  gitBranch: main
services:
- serviceName: project.testautocommitenabled1809.integrations:LOWER
  packages:
  - name: TestAutoCommitEnabled1809Project
    version: "1.0"
- serviceName: pub.string:toLower
  packages:
  - name: WmPublic
    version: 12.1.0.0.1143
- serviceName: pub.flow:debugLog
  packages:
  - name: WmPublic
    version: 12.1.0.0.1143
